<?php

function cipher_menu(){
    $items = array();
    $items['encode'] = array(
        'title' => 'Encode A Message',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('encode_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items['encode_success_page'] = array(
        'title' => 'Get Your Encoded Message',
        'page callback' => 'encode_success',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    $items['decode'] = array(
        'title' => 'Decode A Message',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('decode_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items['decode_success_page'] = array(
        'title' => 'Get Your Decoded Message',
        'page callback' => 'decode_success',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
  return $items;
}

function encode_form(){
    $form['shift_value'] = array(
        '#title' => 'Shift Value',
        '#type' => 'textfield',
        '#description' => t('Enter the amount you want the cipher to shift, or leave it blank for a random amount.'),
        '#element_validate' => array('element_validate_integer_positive'),
    );
    $form['shift_direction'] = array(
        '#title' => 'Shift Direction',
        '#type' => 'textfield',
        '#description' => t('Enter the direction you want the cipher to shift, right or left or leave it blank for a random direction.'),
        '#element_validate' => array('element_validate_right_or_left'),
    );
    $form['phrase_to_encode'] = array(
        '#title' => 'Phrase To Encode',
        '#type' => 'textfield',
        '#description' => t('Enter the phrase you wish to encode.'),
        '#element_validate' => array('element_validate_no_funky_chars'),
        '#required' => TRUE,
    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Encipher Phrase',
    );
    return $form;
}

function decode_form(){
    $form['shift_value'] = array(
        '#title' => 'Shift Value',
        '#type' => 'textfield',
        '#description' => t('Enter the amount that the cipher was shifted.'),
        '#element_validate' => array('element_validate_integer_positive_or_empty'),
        '#required' => TRUE,
    );
    $form['shift_direction'] = array(
        '#title' => 'Shift Direction',
        '#type' => 'textfield',
        '#description' => t('Enter the direction the original phrase was shifted.'),
        '#element_validate' => array('element_validate_right_or_left'),
        '#required' => TRUE,
    );
    $form['phrase_to_decode'] = array(
        '#title' => 'Phrase To Decode',
        '#type' => 'textfield',
        '#description' => t('Enter the phrase you wish to decode.'),
        '#element_validate' => array('element_validate_no_funky_chars'),
        '#required' => TRUE,
    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Decipher Phrase',
    );
    return $form;
}

function element_validate_integer_positive_or_empty($element){
    $value = $element['#value'];
    if ((intval($value) != $value) && ($value < 1)) {
        form_error($element, t('%name must be a positive integer.', array('%name' => $element['#title'])));
    }
}

function element_validate_right_or_left($element){
    if($element['#value']!='left' && $element['#value']!='right' && $element['#value']!=''){
        form_error($element, t('Valid entries are "right" and "left".'));
    }
}

function element_validate_no_funky_chars($element){
    if(!preg_match('/^[a-z0-9 :,.!().?";\'-]+$/i', $element['#value'])){
        form_error($element, t('Valid entries are alphanumeric characters and punctuation.'));
    }
}

function encode_form_submit($form, &$form_state){
    $shift_value = $form_state['values']['shift_value'];
    $shift_direction = $form_state['values']['shift_direction'];
    $phrase_to_encode = $form_state['values']['phrase_to_encode'];
    if($shift_value === ''){
        $shift_value = rand(1, 26);
    }
    if($shift_direction === ''){
        $rand = rand(1,2);
        if($rand === 1){
            $shift_direction = 'left';
        } else {
            $shift_direction = 'right';
        }
    }
    $output = array();
    $output = encode_decode($shift_value, $shift_direction, $phrase_to_encode);
    $_SESSION['shift_value'] = $output[0];
    $_SESSION['shift_direction'] = $output[1];
    $_SESSION['encoded_string'] = $output[2];
    $form_state['redirect'] = 'encode_success_page';
}

function decode_form_submit($form, &$form_state){
    $shift_value = $form_state['values']['shift_value'];
    $shift_direction = $form_state['values']['shift_direction'];
    $phrase_to_decode = $form_state['values']['phrase_to_decode'];
    $output = array();
    if ($shift_direction === 'left'){
        $output = encode_decode($shift_value, 'right', $phrase_to_decode);
    } else {
        $output = encode_decode($shift_value, 'left', $phrase_to_decode);
    }
    $_SESSION['shift_value'] = $output[0];
    $_SESSION['shift_direction'] = $output[1];
    $_SESSION['decoded_string'] = $output[2];
    $form_state['redirect'] = 'decode_success_page';
}

function encode_decode($shift_value, $shift_direction, $phrase){
    $letters = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ';
    $shift_value = (int)$shift_value % 26;
    for ($index = 0, $length = strlen($phrase); $index < $length; $index++) {
        $char = $phrase[$index];
        if($shift_direction === 'right'){
            if ($char >= 'a' && $char <= 'z') {
                $phrase[$index] = $letters[(ord($char) - 71 + $shift_value) % 26];
            } else if ($char >= 'A' && $char <= 'Z') {
                $phrase[$index] = $letters[(ord($char) - 39 + $shift_value) % 26];
            }
        } else {
            if ($char >= 'a' && $char <= 'z') {
                $phrase[$index] = $letters[(ord($char) - 71 - $shift_value) % 26];
            } else if ($char >= 'A' && $char <= 'Z') {
                $phrase[$index] = $letters[(ord($char) - 39 - $shift_value) % 26];
            }
        }
    }
    return array($shift_value, $shift_direction, $phrase);
}

function encode_success(){
    return '<p>Huzzah, you have encoded a phrase with the following keys:<p>
            <p>Shift Value: '.$_SESSION['shift_value'].'</p>
            <p>Shift Direction: '.$_SESSION['shift_direction'].'</p>
            <p>The phrase thus encoded reads:</p>
            <h3>'.$_SESSION['encoded_string'].'</h3>
            <p>Keep It Secret, Keep it Safe!</p>';
}

function decode_success(){
    return '<p>Huzzah, you have encoded a phrase with the following keys:<p>
            <p>Shift Value: '.$_SESSION['shift_value'].'</p>
            <p>Shift Direction: '.$_SESSION['shift_direction'].'</p>
            <p>The phrase thus encoded reads:</p>
            <h3>'.$_SESSION['decoded_string'].'</h3>
            <p>Keep It Secret, Keep it Safe!</p>';
}
